"""Dependency-free inline SVG charts.

Why hand-rolled SVG rather than matplotlib:

* **No dependency.** A teammate who only wants the contracts should not need a
  plotting stack, and `pip install matplotlib` is not free on a hackathon laptop.
* **Smaller and sharper.** A PNG has to be base64-embedded, costing about a third
  more bytes than its binary size, and it is fixed-resolution. Inline SVG is text,
  compresses well, and stays crisp.
* **Theme-aware.** The charts use CSS custom properties, so they follow the report's
  light or dark palette instead of shipping a baked-in white background that glares
  in dark mode.

The four shapes here are the ones `EXPECTED_VIZ` actually asks for across the
stages: a ranked bar, a heatmap, a distribution, and a scatter. Each returns an SVG
string and a matching ``Visualization``, so the declared encoding is generated by
the same code that draws the marks.

Everything is deliberately plain. These are report figures, not an interactive
plotting library; when a stage needs something genuinely bespoke it should write it
and declare its own encoding.
"""

from __future__ import annotations

import html
import math
from collections.abc import Sequence
from pathlib import Path

from reagent.contracts import ColorMap, Visualization, VizKind, VizMedium

#: Okabe-Ito, the same colour-blind-safe palette the graph renderer uses, so a
#: report's figures read as one system rather than as separate tools' output.
PALETTE = ["#0072B2", "#E69F00", "#009E73", "#CC79A7", "#56B4E9", "#D55E00",
           "#6A3D9A", "#454545"]

#: Sequential ramp for heatmaps. Light-to-dark blue: monotonic in lightness, so it
#: survives greyscale printing, which a rainbow ramp does not.
SEQUENTIAL = ["#f2f7fb", "#d5e5f2", "#a9cbe4", "#74a9d0", "#4180b8", "#1f5c99", "#0d3b6b"]

_CSS = """
  .rg-chart { font: 12px -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }
  .rg-chart text { fill: var(--ink, #1a1a1a); }
  .rg-chart .ax { stroke: var(--line, #d8d8d4); stroke-width: 1; }
  .rg-chart .grid { stroke: var(--line, #e8e8e4); stroke-width: 1; stroke-dasharray: 2 3; }
  .rg-chart .lab { font-size: 11px; fill: var(--muted, #5c5c5c); }
  .rg-chart .val { font-size: 10.5px; fill: var(--muted, #5c5c5c); }
  .rg-chart .ttl { font-size: 12.5px; font-weight: 600; }
"""


def _e(s: object) -> str:
    return html.escape(str(s), quote=True)


def _svg(w: int, h: int, body: str) -> str:
    return (
        f'<svg class="rg-chart" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" '
        f'width="100%" role="img"><style>{_CSS}</style>{body}</svg>'
    )


def _nice_ticks(lo: float, hi: float, n: int = 5) -> list[float]:
    """Round tick values. An axis labelled 0, 0.1732, 0.3464 is not readable."""
    if hi <= lo:
        return [lo]
    raw = (hi - lo) / max(1, n)
    mag = 10 ** math.floor(math.log10(raw))
    step = min((m * mag for m in (1, 2, 2.5, 5, 10) if m * mag >= raw), default=raw)
    start = math.floor(lo / step) * step
    out, v = [], start
    while v <= hi + step / 2:
        out.append(round(v, 10))
        v += step
    return out


def _write(svg: str, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as fh:
        fh.write(svg)
    return path


# --------------------------------------------------------------------------


def ranked_bar(
    labels: Sequence[str],
    values: Sequence[float],
    out_path: Path,
    *,
    viz_id: str,
    title: str,
    question: str,
    takeaway: str,
    reads_from: Sequence[str],
    value_label: str = "value",
    covers_metrics: Sequence[str] = (),
    highlight: Sequence[int] = (),
    repo_root: Path | None = None,
) -> tuple[Path, Visualization]:
    """Horizontal ranked bars. The right shape for "which of these is biggest".

    Sorted descending, because an unsorted ranked chart makes the reader do the
    sorting. ``highlight`` marks indices worth the reader's attention in a second
    colour.
    """
    order = sorted(range(len(values)), key=lambda i: -values[i])
    labels = [labels[i] for i in order]
    values = [values[i] for i in order]
    hl = {order.index(i) for i in highlight if i < len(order)}

    row, pad_l, pad_r, pad_t, pad_b = 22, 190, 60, 34, 34
    w = 760
    h = pad_t + row * len(values) + pad_b
    plot_w = w - pad_l - pad_r
    vmax = max(values) if values else 1.0
    vmax = vmax if vmax > 0 else 1.0

    parts = [f'<text class="ttl" x="8" y="18">{_e(title)}</text>']
    for t in _nice_ticks(0, vmax):
        x = pad_l + plot_w * (t / vmax)
        parts.append(f'<line class="grid" x1="{x:.1f}" y1="{pad_t}" x2="{x:.1f}" y2="{h - pad_b}"/>')
        parts.append(f'<text class="val" x="{x:.1f}" y="{h - pad_b + 14}" text-anchor="middle">{t:g}</text>')

    for i, (lab, val) in enumerate(zip(labels, values, strict=True)):
        y = pad_t + i * row
        bw = plot_w * (val / vmax)
        color = PALETTE[1] if i in hl else PALETTE[0]
        parts.append(
            f'<text class="lab" x="{pad_l - 8}" y="{y + row / 2 + 4:.1f}" '
            f'text-anchor="end">{_e(lab[:34])}</text>'
        )
        parts.append(
            f'<rect x="{pad_l}" y="{y + 3:.1f}" width="{bw:.1f}" height="{row - 7}" '
            f'fill="{color}" rx="2"><title>{_e(lab)}: {val:g}</title></rect>'
        )
        parts.append(
            f'<text class="val" x="{pad_l + bw + 6:.1f}" y="{y + row / 2 + 4:.1f}">{val:g}</text>'
        )
    parts.append(f'<line class="ax" x1="{pad_l}" y1="{pad_t}" x2="{pad_l}" y2="{h - pad_b}"/>')
    parts.append(
        f'<text class="lab" x="{pad_l + plot_w / 2:.1f}" y="{h - 6}" '
        f'text-anchor="middle">{_e(value_label)}</text>'
    )

    path = _write(_svg(w, h, "".join(parts)), out_path)
    viz = Visualization(
        id=viz_id, kind=VizKind.RANKED_BAR, medium=VizMedium.SVG, title=title,
        question=question, takeaway=takeaway,
        path=_rel(path, repo_root), reads_from=list(reads_from),
        encoding={"bar_length": value_label, "bar_order": "descending by value",
                  "bar_fill": "highlighted vs not"},
        alt_text=(
            f"A horizontal bar chart of {len(values)} items ranked by {value_label}, "
            f"from {max(values):g} at the top down to {min(values):g}."
            if values else "An empty bar chart: no items to rank."
        ),
        n_elements=len(values), covers_metrics=list(covers_metrics),
    )
    return path, viz


def heatmap(
    row_labels: Sequence[str],
    col_labels: Sequence[str],
    matrix: Sequence[Sequence[float | None]],
    out_path: Path,
    *,
    viz_id: str,
    title: str,
    question: str,
    takeaway: str,
    reads_from: Sequence[str],
    value_label: str = "score",
    covers_metrics: Sequence[str] = (),
    repo_root: Path | None = None,
) -> tuple[Path, Visualization]:
    """Row-by-column matrix on a monotonic sequential ramp.

    ``None`` cells render as an explicit hatch rather than as zero. Conflating
    "not measured" with "measured zero" is the single most common way a heatmap
    lies, and it matters here because an unpopulated similarity axis is a finding.
    """
    cell, pad_l, pad_t, pad_r, pad_b = 30, 200, 78, 24, 46
    w = pad_l + cell * len(col_labels) + pad_r
    h = pad_t + cell * len(row_labels) + pad_b

    flat = [v for r in matrix for v in r if v is not None]
    lo, hi = (min(flat), max(flat)) if flat else (0.0, 1.0)
    span = (hi - lo) or 1.0

    parts = [
        f'<text class="ttl" x="8" y="18">{_e(title)}</text>',
        '<defs><pattern id="na" width="6" height="6" patternUnits="userSpaceOnUse" '
        'patternTransform="rotate(45)"><line x1="0" y1="0" x2="0" y2="6" '
        'stroke="var(--line,#d0d0cc)" stroke-width="2"/></pattern></defs>',
    ]
    for j, c in enumerate(col_labels):
        x = pad_l + j * cell + cell / 2
        parts.append(
            f'<text class="lab" transform="translate({x:.1f},{pad_t - 8}) rotate(-45)" '
            f'text-anchor="start">{_e(c[:18])}</text>'
        )
    for i, r in enumerate(row_labels):
        y = pad_t + i * cell
        parts.append(
            f'<text class="lab" x="{pad_l - 8}" y="{y + cell / 2 + 4:.1f}" '
            f'text-anchor="end">{_e(r[:30])}</text>'
        )
        for j in range(len(col_labels)):
            v = matrix[i][j] if j < len(matrix[i]) else None
            x = pad_l + j * cell
            if v is None:
                fill, tip = "url(#na)", "not measured"
            else:
                idx = min(len(SEQUENTIAL) - 1, int((v - lo) / span * (len(SEQUENTIAL) - 1) + 0.5))
                fill, tip = SEQUENTIAL[idx], f"{v:g}"
            parts.append(
                f'<rect x="{x}" y="{y}" width="{cell - 2}" height="{cell - 2}" fill="{fill}" '
                f'rx="2"><title>{_e(r)} / {_e(col_labels[j])}: {_e(tip)}</title></rect>'
            )

    # Legend: the ramp plus its domain, so a colour can be read back to a number.
    lx, ly = pad_l, h - 26
    for k, c in enumerate(SEQUENTIAL):
        parts.append(f'<rect x="{lx + k * 22}" y="{ly}" width="22" height="10" fill="{c}"/>')
    parts += [
        f'<text class="val" x="{lx}" y="{ly + 22}">{lo:g}</text>',
        f'<text class="val" x="{lx + len(SEQUENTIAL) * 22}" y="{ly + 22}" '
        f'text-anchor="end">{hi:g} {_e(value_label)}</text>',
        f'<rect x="{lx + len(SEQUENTIAL) * 22 + 24}" y="{ly}" width="16" height="10" '
        f'fill="url(#na)"/>',
        f'<text class="val" x="{lx + len(SEQUENTIAL) * 22 + 44}" y="{ly + 9}">not measured</text>',
    ]

    path = _write(_svg(w, h, "".join(parts)), out_path)
    n_missing = sum(1 for r in matrix for v in r if v is None)
    viz = Visualization(
        id=viz_id, kind=VizKind.HEATMAP, medium=VizMedium.SVG, title=title,
        question=question, takeaway=takeaway,
        path=_rel(path, repo_root), reads_from=list(reads_from),
        encoding={"cell_fill": value_label, "row": "entity", "column": "axis or condition",
                  "hatched_cell": "not measured (never zero)"},
        color_maps=[ColorMap(channel="cell_fill", data_field=value_label,
                             scale_type="sequential", domain=(lo, hi))],
        alt_text=(
            f"A {len(row_labels)}-row by {len(col_labels)}-column heatmap of {value_label}, "
            f"shaded light to dark over {lo:g} to {hi:g}. {n_missing} cells are hatched "
            "to mark values that were not measured, as distinct from zero."
        ),
        n_elements=len(row_labels) * len(col_labels), covers_metrics=list(covers_metrics),
    )
    return path, viz


def histogram(
    values: Sequence[float],
    out_path: Path,
    *,
    viz_id: str,
    title: str,
    question: str,
    takeaway: str,
    reads_from: Sequence[str],
    bins: int = 20,
    value_label: str = "value",
    markers: Sequence[tuple[float, str]] = (),
    covers_metrics: Sequence[str] = (),
    repo_root: Path | None = None,
) -> tuple[Path, Visualization]:
    """A distribution, with optional labelled vertical markers.

    This is the shape that replaces a reported mean. Bimodality is frequently the
    finding, and a mean hides it — which is why the domain-shift measurement is
    specified as a distribution rather than a summary statistic.
    """
    w, h, pad_l, pad_r, pad_t, pad_b = 720, 300, 52, 24, 34, 46
    plot_w, plot_h = w - pad_l - pad_r, h - pad_t - pad_b
    if not values:
        return _write(_svg(w, h, '<text class="lab" x="20" y="40">no values</text>'), out_path), None  # type: ignore[return-value]

    lo, hi = min(values), max(values)
    span = (hi - lo) or 1.0
    counts = [0] * bins
    for v in values:
        counts[min(bins - 1, int((v - lo) / span * bins))] += 1
    cmax = max(counts) or 1
    bw = plot_w / bins

    parts = [f'<text class="ttl" x="8" y="18">{_e(title)}</text>']
    for t in _nice_ticks(0, cmax, 4):
        y = pad_t + plot_h - plot_h * (t / cmax)
        parts.append(f'<line class="grid" x1="{pad_l}" y1="{y:.1f}" x2="{w - pad_r}" y2="{y:.1f}"/>')
        parts.append(f'<text class="val" x="{pad_l - 6}" y="{y + 4:.1f}" text-anchor="end">{t:g}</text>')

    for i, c in enumerate(counts):
        bh = plot_h * (c / cmax)
        x = pad_l + i * bw
        b_lo, b_hi = lo + span * i / bins, lo + span * (i + 1) / bins
        parts.append(
            f'<rect x="{x:.1f}" y="{pad_t + plot_h - bh:.1f}" width="{bw - 1:.1f}" '
            f'height="{bh:.1f}" fill="{PALETTE[0]}" opacity="0.85">'
            f'<title>{b_lo:.3g} to {b_hi:.3g}: {c}</title></rect>'
        )

    for mv, mlab in markers:
        x = pad_l + plot_w * ((mv - lo) / span)
        parts += [
            f'<line x1="{x:.1f}" y1="{pad_t}" x2="{x:.1f}" y2="{pad_t + plot_h}" '
            f'stroke="{PALETTE[5]}" stroke-width="1.6" stroke-dasharray="5 3"/>',
            f'<text class="val" x="{x + 4:.1f}" y="{pad_t + 12}" fill="{PALETTE[5]}">{_e(mlab)}</text>',
        ]

    for t in _nice_ticks(lo, hi, 6):
        x = pad_l + plot_w * ((t - lo) / span)
        parts.append(f'<text class="val" x="{x:.1f}" y="{h - pad_b + 16}" text-anchor="middle">{t:g}</text>')
    parts += [
        f'<line class="ax" x1="{pad_l}" y1="{pad_t + plot_h}" x2="{w - pad_r}" y2="{pad_t + plot_h}"/>',
        f'<line class="ax" x1="{pad_l}" y1="{pad_t}" x2="{pad_l}" y2="{pad_t + plot_h}"/>',
        f'<text class="lab" x="{pad_l + plot_w / 2:.1f}" y="{h - 6}" text-anchor="middle">{_e(value_label)}</text>',
        f'<text class="lab" transform="translate(14,{pad_t + plot_h / 2:.1f}) rotate(-90)" '
        f'text-anchor="middle">count</text>',
    ]

    srt = sorted(values)
    median = srt[len(srt) // 2]
    path = _write(_svg(w, h, "".join(parts)), out_path)
    viz = Visualization(
        id=viz_id, kind=VizKind.DISTRIBUTION, medium=VizMedium.SVG, title=title,
        question=question, takeaway=takeaway,
        path=_rel(path, repo_root), reads_from=list(reads_from),
        encoding={"bar_height": "count of items in bin", "x_position": value_label},
        alt_text=(
            f"A histogram of {len(values)} values of {value_label} in {bins} bins, "
            f"spanning {lo:.3g} to {hi:.3g} with a median of {median:.3g}."
            + (f" Marked: {', '.join(m[1] for m in markers)}." if markers else "")
        ),
        n_elements=len(values), covers_metrics=list(covers_metrics),
        params={"bins": bins, "aggregated": True},
    )
    return path, viz


def scatter(
    xs: Sequence[float],
    ys: Sequence[float],
    out_path: Path,
    *,
    viz_id: str,
    title: str,
    question: str,
    takeaway: str,
    reads_from: Sequence[str],
    x_label: str = "x",
    y_label: str = "y",
    labels: Sequence[str] = (),
    groups: Sequence[str] = (),
    covers_metrics: Sequence[str] = (),
    repo_root: Path | None = None,
) -> tuple[Path, Visualization]:
    """A scatter, optionally grouped by colour. The shape for "does X predict Y".

    Groups are capped at the palette length; beyond that colour stops
    discriminating, and the contract's ColorMap validator would reject it anyway.
    """
    w, h, pad_l, pad_r, pad_t, pad_b = 640, 420, 58, 110, 34, 48
    plot_w, plot_h = w - pad_l - pad_r, h - pad_t - pad_b
    if not xs:
        return _write(_svg(w, h, '<text class="lab" x="20" y="40">no points</text>'), out_path), None  # type: ignore[return-value]

    xlo, xhi = min(xs), max(xs)
    ylo, yhi = min(ys), max(ys)
    xs_span, ys_span = (xhi - xlo) or 1.0, (yhi - ylo) or 1.0
    uniq = sorted(set(groups)) if groups else []
    cmap = {g: PALETTE[i % len(PALETTE)] for i, g in enumerate(uniq)}

    parts = [f'<text class="ttl" x="8" y="18">{_e(title)}</text>']
    for t in _nice_ticks(ylo, yhi, 5):
        y = pad_t + plot_h - plot_h * ((t - ylo) / ys_span)
        parts.append(f'<line class="grid" x1="{pad_l}" y1="{y:.1f}" x2="{pad_l + plot_w}" y2="{y:.1f}"/>')
        parts.append(f'<text class="val" x="{pad_l - 6}" y="{y + 4:.1f}" text-anchor="end">{t:g}</text>')
    for t in _nice_ticks(xlo, xhi, 5):
        x = pad_l + plot_w * ((t - xlo) / xs_span)
        parts.append(f'<text class="val" x="{x:.1f}" y="{pad_t + plot_h + 16}" text-anchor="middle">{t:g}</text>')

    for i, (px, py) in enumerate(zip(xs, ys, strict=True)):
        cx = pad_l + plot_w * ((px - xlo) / xs_span)
        cy = pad_t + plot_h - plot_h * ((py - ylo) / ys_span)
        g = groups[i] if i < len(groups) else None
        color = cmap.get(g, PALETTE[0]) if g else PALETTE[0]
        tip = labels[i] if i < len(labels) else f"({px:g}, {py:g})"
        parts.append(
            f'<circle cx="{cx:.1f}" cy="{cy:.1f}" r="4" fill="{color}" opacity="0.8">'
            f'<title>{_e(tip)}: {px:g}, {py:g}</title></circle>'
        )

    for k, g in enumerate(uniq[:len(PALETTE)]):
        ly = pad_t + 14 + k * 18
        parts += [
            f'<circle cx="{pad_l + plot_w + 18}" cy="{ly - 4}" r="4" fill="{cmap[g]}"/>',
            f'<text class="val" x="{pad_l + plot_w + 28}" y="{ly}">{_e(g[:14])}</text>',
        ]

    parts += [
        f'<line class="ax" x1="{pad_l}" y1="{pad_t + plot_h}" x2="{pad_l + plot_w}" y2="{pad_t + plot_h}"/>',
        f'<line class="ax" x1="{pad_l}" y1="{pad_t}" x2="{pad_l}" y2="{pad_t + plot_h}"/>',
        f'<text class="lab" x="{pad_l + plot_w / 2:.1f}" y="{h - 8}" text-anchor="middle">{_e(x_label)}</text>',
        f'<text class="lab" transform="translate(16,{pad_t + plot_h / 2:.1f}) rotate(-90)" '
        f'text-anchor="middle">{_e(y_label)}</text>',
    ]

    path = _write(_svg(w, h, "".join(parts)), out_path)
    enc = {"x_position": x_label, "y_position": y_label}
    cmaps = []
    if uniq:
        enc["point_fill"] = "group"
        cmaps.append(ColorMap(channel="point_fill", data_field="group",
                              scale_type="categorical", mapping=cmap))
    viz = Visualization(
        id=viz_id, kind=VizKind.SCATTER, medium=VizMedium.SVG, title=title,
        question=question, takeaway=takeaway,
        path=_rel(path, repo_root), reads_from=list(reads_from),
        encoding=enc, color_maps=cmaps,
        alt_text=(
            f"A scatter plot of {len(xs)} points with {x_label} on the horizontal axis "
            f"({xlo:.3g} to {xhi:.3g}) and {y_label} on the vertical ({ylo:.3g} to {yhi:.3g})"
            + (f", coloured by {len(uniq)} groups." if uniq else ".")
        ),
        n_elements=len(xs), covers_metrics=list(covers_metrics),
    )
    return path, viz


def _rel(path: Path, repo_root: Path | None) -> str:
    root = Path(repo_root or Path.cwd())
    try:
        return str(path.relative_to(root)).replace("\\", "/")
    except ValueError:
        return str(path).replace("\\", "/")
